
export const doctorsData = [
  {
    id: 1,
    name: "Dr. Priya Sharma",
    specialty: "Cardiology",
    hospital: "Apollo Hospital",
    city: "Mumbai",
    status: "available",
    timing: "9:00 AM - 5:00 PM",
    qualifications: "MD, DM Cardiology",
    experience: "15 years",
    lastUpdated: "2 mins ago",
    phone: "+91 98765 43210",
    email: "priya.sharma@apollo.com",
    photo: ""
  },
  {
    id: 2,
    name: "Dr. Rajesh Kumar",
    specialty: "Orthopedics",
    hospital: "Fortis Hospital",
    city: "Delhi",
    status: "unavailable",
    timing: "10:00 AM - 6:00 PM",
    qualifications: "MS Orthopedics",
    experience: "12 years",
    lastUpdated: "5 mins ago",
    phone: "+91 98765 43211",
    email: "rajesh.kumar@fortis.com",
    photo: ""
  },
  {
    id: 3,
    name: "Dr. Anita Desai",
    specialty: "Pediatrics",
    hospital: "Lilavati Hospital",
    city: "Mumbai",
    status: "on-leave",
    timing: "8:00 AM - 2:00 PM",
    qualifications: "MD Pediatrics",
    experience: "20 years",
    lastUpdated: "1 hour ago",
    phone: "+91 98765 43212",
    email: "anita.desai@lilavati.com",
    photo: ""
  },
  {
    id: 4,
    name: "Dr. Suresh Reddy",
    specialty: "Neurology",
    hospital: "Apollo Hospital",
    city: "Hyderabad",
    status: "available",
    timing: "11:00 AM - 7:00 PM",
    qualifications: "DM Neurology",
    experience: "18 years",
    lastUpdated: "Just now",
    phone: "+91 98765 43213",
    email: "suresh.reddy@apollo.com",
    photo: ""
  },
  {
    id: 5,
    name: "Dr. Meera Patel",
    specialty: "Dermatology",
    hospital: "Max Hospital",
    city: "Delhi",
    status: "available",
    timing: "9:30 AM - 4:30 PM",
    qualifications: "MD Dermatology",
    experience: "10 years",
    lastUpdated: "3 mins ago",
    phone: "+91 98765 43214",
    email: "meera.patel@max.com",
    photo: ""
  },
  {
    id: 6,
    name: "Dr. Arjun Singh",
    specialty: "Emergency Medicine",
    hospital: "Fortis Hospital",
    city: "Bangalore",
    status: "available",
    timing: "24/7 Emergency",
    qualifications: "MD Emergency Medicine",
    experience: "8 years",
    lastUpdated: "1 min ago",
    phone: "+91 98765 43215",
    email: "arjun.singh@fortis.com",
    photo: ""
  },
  {
    id: 7,
    name: "Dr. Kavitha Nair",
    specialty: "Gynecology",
    hospital: "Manipal Hospital",
    city: "Bangalore",
    status: "unavailable",
    timing: "10:00 AM - 5:00 PM",
    qualifications: "MD Gynecology",
    experience: "14 years",
    lastUpdated: "10 mins ago",
    phone: "+91 98765 43216",
    email: "kavitha.nair@manipal.com",
    photo: ""
  },
  {
    id: 8,
    name: "Dr. Amit Joshi",
    specialty: "Cardiology",
    hospital: "Ruby Hall Clinic",
    city: "Pune",
    status: "on-leave",
    timing: "8:00 AM - 4:00 PM",
    qualifications: "DM Cardiology",
    experience: "22 years",
    lastUpdated: "2 hours ago",
    phone: "+91 98765 43217",
    email: "amit.joshi@rubyhall.com",
    photo: ""
  },
  {
    id: 9,
    name: "Dr. Sunita Mehta",
    specialty: "ENT",
    hospital: "Kerala City Hospital",
    city: "Kochi",
    status: "available",
    timing: "9:00 AM - 6:00 PM",
    qualifications: "MS ENT",
    experience: "16 years",
    lastUpdated: "5 mins ago",
    phone: "+91 98765 43218",
    email: "sunita.mehta@keralacity.com",
    photo: ""
  },
  {
    id: 10,
    name: "Dr. Vikram Gupta",
    specialty: "Psychiatry",
    hospital: "Delhi Care Centre",
    city: "Delhi",
    status: "available",
    timing: "11:00 AM - 7:00 PM",
    qualifications: "MD Psychiatry",
    experience: "13 years",
    lastUpdated: "Just now",
    phone: "+91 98765 43219",
    email: "vikram.gupta@delhicare.com",
    photo: ""
  },
  {
    id: 11,
    name: "Dr. Ravi Chandra",
    specialty: "Urology",
    hospital: "Chennai Medical Center",
    city: "Chennai",
    status: "on-leave",
    timing: "8:30 AM - 5:30 PM",
    qualifications: "MCh Urology",
    experience: "19 years",
    lastUpdated: "30 mins ago",
    phone: "+91 98765 43220",
    email: "ravi.chandra@chennaimedical.com",
    photo: ""
  }
];
